apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: springboot-app-ns 
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: viz55/project-cicd:16
        ports:
        - containerPort: 8080
